// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13Vh8zQcLT-y51TWU2H0IvXqymPVDqeA',
    appId: '1:532210875865:web:9dd00c574469147f342dc8',
    messagingSenderId: '532210875865',
    projectId: 'smart-greenhouse-24953',
    authDomain: 'smart-greenhouse-24953.firebaseapp.com',
    storageBucket: 'smart-greenhouse-24953.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUyIhRvk8sRz9EOBLd3Vku7YoyIOvOHU',
    appId: '1:532210875865:android:455a6052dfc12968342dc8',
    messagingSenderId: '532210875865',
    projectId: 'smart-greenhouse-24953',
    storageBucket: 'smart-greenhouse-24953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7Xhctjp1CVAb52KA4nUNBUhYMKFZLBo',
    appId: '1:532210875865:ios:8b837bdf73fbcfb7342dc8',
    messagingSenderId: '532210875865',
    projectId: 'smart-greenhouse-24953',
    storageBucket: 'smart-greenhouse-24953.firebasestorage.app',
    iosBundleId: 'com.example.smartGreenhouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7Xhctjp1CVAb52KA4nUNBUhYMKFZLBo',
    appId: '1:532210875865:ios:8b837bdf73fbcfb7342dc8',
    messagingSenderId: '532210875865',
    projectId: 'smart-greenhouse-24953',
    storageBucket: 'smart-greenhouse-24953.firebasestorage.app',
    iosBundleId: 'com.example.smartGreenhouseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13Vh8zQcLT-y51TWU2H0IvXqymPVDqeA',
    appId: '1:532210875865:web:b8dd23801d89e49b342dc8',
    messagingSenderId: '532210875865',
    projectId: 'smart-greenhouse-24953',
    authDomain: 'smart-greenhouse-24953.firebaseapp.com',
    storageBucket: 'smart-greenhouse-24953.firebasestorage.app',
  );
}
